version: '3.3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: 'challenge'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    volumes:
      - database

  api:
    build: .
    volumes:
      - ./:/app
    ports:
      - 3000:3000

volumes:
  database:
