version: '3.4'
services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    env_file: .env

  api:
    container_name: api
    build:
      context: .
      target: development
    volumes:
      - .:/app
    command: npm run start:dev && npm run migration:run
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      - db
